name: Update README with Random Quote

on:
  schedule:
    # Planifiez l'exécution à 00h00 chaque jour (UTC)
    - cron:  '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update README
      run: python update_readme.py
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git diff
        git add -A
        git commit -m "Update README with random quote" || exit 0
        git push
